"""Added timestamp to Comment model

Revision ID: 8e968d1e39dd
Revises: 33d03c2f6176
Create Date: 2019-05-16 17:32:19.838292

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e968d1e39dd'
down_revision = '33d03c2f6176'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('created_on', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_comment_created_on'), 'comment', ['created_on'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_comment_created_on'), table_name='comment')
    op.drop_column('comment', 'created_on')
    # ### end Alembic commands ###
